version: '3.1'
services:
  postgres-graphql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: graphqldemo
      POSTGRES_USER: graphqldemo
      POSTGRES_DB: graphqldemo
  redis-graphql:
      image: redis:latest
      ports:
      - 6379:6379
      environment:
      - REDIS_REPLICATION_MODE=master
