// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type UserWhereInput struct {
	Name string `json:"name"`
}
